### ISSUE TITLE
Security of this project

### ISSUE THREAD

**Issue by kurzai** [stanvanrooy/linkauto#1]
Hey there!
I've been going through the source code to get an idea of how you're accessing the linkedin api directly, since I'm working on a linkedin automation (nodejs based) myself.
I was just wondering if you've got any idea of how safe this method is, i.e. would linkedin be able to tell, through network traffic analysis, that those requests were not made by their platform directly? I just want to avoid getting my account banned.

Thanks for putting this up for everyone to use, keep it up!

**Comment by stanvanrooy** [comment]
Congrats on opening the first issue :)

Simulating the behaviour of a mobile user, is, from my [experience with Instagram](https://github.com/stanvanrooy/instauto), a lot 'safer' then simulating browser behaviour.

Usually, the anti-bot protection is toned down quite a bit for mobile apps, but of course it's still possible to get flagged as a bot.

What I'm trying to do with this package, is mimicking the behavior of the mobile app as much as possible, methods of doing this, include:
1. Simulating pre/post action behaviour, i.e. if you send a connection request, you first simulate visiting that account.
2. Sending analytics requests, just like the app does every xx seconds
3. Sending the correct requests, copy the request made by the app 1 for 1.

If all that is correctly done, it should be pretty safe. You can do the same thing for the browser, but from my experience, that is a lot harder.
