### ISSUE TITLE
Missing Closed Bracket in User Agent?

### ISSUE THREAD

**Issue by kurzai** [stanvanrooy/linkauto#2]
Hey again :)

I've been going through the source code and noticed, that the get_useragent function in linkauto/api/mixins/helper.py, line 22 is missing a closed bracket (bracket opens in front of "Linux", but never closes)

  ```
def get_useragent(self) -> str:
    return f"{self.config.linkedin_app.appId}/{self.config.linkedin_app.clientMinorVersion} " \
           f"(Linux; U; {self.config.device.androidVersion}; {self.config.device.region}; " \
           f"{self.config.device.model}; Build/NMF26Q; Cronet/{self.config.device.cronetVersion}"
```

Is that on purpose or an error?

**Comment by stanvanrooy** [comment]
That definitely wasn't on purpose. Good catch!
