### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by holts-shoe** [stanvanrooy/linkauto#4]
Howdy. Love the premise of this package. Having trouble using it - running into a ModuleNotFoundError. 
I made sure that the required package versions matched.

Details:

D:\>python
>>> import linkauto
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'linkauto'

D:\>pip list
>>> Package               Version
aiohttp               3.7.4.post0
...
async-timeout         3.0.1
attrs                 20.3.0
...
chardet               4.0.0
...
idna                  2.10
...
linkauto              0.0.1
...
multidict             5.1.0
...
orjson                3.6.4
...
typing-extensions     3.10.0.2
...
yarl                  1.6.3
...

Thanks again for creating this, hope to get to play around with it.

**Comment by stanvanrooy** [comment]
Should be fixed now.
